version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_store:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE

  backend:
    build: ./backend
    container_name: summary-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - chroma
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: summary-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
