version: '3.8'

services:
  chroma:
    build:
      context: .
      dockerfile: chroma.Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - chroma-data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/api/v2/heartbeat || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: 5

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      chroma:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/health || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: 20
      start_period: 120s

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000

volumes:
  chroma-data:
