apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClass | default "gp2" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}