apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-backend
  template:
    metadata:
      labels:
        app: summary-backend
    spec:
      containers:
      - name: backend
        image: summary-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: CHROMA_HOST
          value: chroma
        - name: CHROMA_PORT
          value: "8000"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: summary-backend
spec:
  selector:
    app: summary-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
