apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-frontend
  template:
    metadata:
      labels:
        app: summary-frontend
    spec:
      containers:
      - name: frontend
        image: summary-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: summary-frontend
spec:
  selector:
    app: summary-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
