replicaCount: 1

image:
  repository: 216201940479.dkr.ecr.us-east-2.amazonaws.com/starckai-repo
  tag: "ai_summary_assistant_chroma-latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 1Gi
  storageClass: gp3
  accessModes:
    - ReadWriteOnce

resources: {}
